"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ["../images/green.png",
            "../images/pink.png",
            "../images/yellow.png",
            "../images/black.png",]
OPTIONS = {
    "argv_emulation":False,
    "iconfile":"../images/アイコン.icns",
    "strip":True,
    "includes":["download","record"]
    
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
